services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./locustfile.py:/app/locustfile.py
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
      - "8089:8089"
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-development}
      - PYTHONPATH=/app/apps
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - app_network

  selenium:
    image: selenium/standalone-firefox:4.27.0-20241204
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge