# Generated by Django 5.1.6 on 2025-02-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='title',
            new_name='name',
        ),
    ]
