# Generated by Django 5.1.6 on 2025-02-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0002_rename_title_condition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='-', max_length=30),
            preserve_default=False,
        ),
    ]
