# Generated by Django 5.1.6 on 2025-02-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_type', models.CharField(choices=[('mobility', 'Mobility'), ('specific_need', 'Specific_Need'), ('skill', 'Skill'), ('cause', 'Cause'), ('hobby', 'Hobby')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='valid',
            new_name='is_email_valid',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='created',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='updated',
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='country', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default='job', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='remote',
            field=models.CharField(choices=[('full_remote', 'Full_Remote'), ('no_remote', 'No_Remote'), ('hybrid', 'Hybrid'), ('no_pref', 'No_Pref')], default='no_pref', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rqth',
            field=models.CharField(choices=[('with_rqth', 'With_RQTH'), ('without_rqth', 'Without_RQTH'), ('dont_say', 'Dont_Say')], default='dont_say', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='special_needs_comments',
            field=models.CharField(default='special_needs_comments', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user'),
        ),
        migrations.CreateModel(
            name='CandidateAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neuroa_app.attribute')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neuroa_app.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('pro', 'Pro'), ('personal', 'Personal'), ('training', 'Training')], max_length=20)),
                ('organization', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('experience_contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('self_employed', 'Self_Employed'), ('internship', 'Internship'), ('work_study', 'Work_Study'), ('civic_service', 'Civic_Service'), ('other', 'Other')], default='other', max_length=50)),
                ('is_part_time', models.BooleanField(default=False, verbose_name='Part-time')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current_position', models.BooleanField(default=False, verbose_name='Current position')),
                ('url', models.URLField(blank=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neuroa_app.candidate')),
            ],
        ),
    ]
