# Generated by Django 5.1.6 on 2025-02-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0007_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='neuroa_app.candidate'),
        ),
    ]
