# Generated by Django 5.1.6 on 2025-02-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0008_alter_experience_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateattribute',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='neuroa_app.candidate'),
        ),
    ]
