# Generated by Django 5.1.6 on 2025-02-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0005_alter_user_token'),
        ('neuroa_app', '0010_remove_attribute_description_and_more'),
    ]

    operations = [
    ]
