# Generated by Django 5.1.6 on 2025-02-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0013_company_joboffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='remote',
            new_name='remotes',
        ),
    ]
