# Generated by Django 5.1.6 on 2025-03-03 14:48

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0015_experience_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'entreprise'},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': "offre d'emploi", 'verbose_name_plural': "offres d'emploi"},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('mobility', 'Mobilité'), ('specific_need', 'Besoin spécifique'), ('skill', 'Compétence'), ('cause', 'Cause'), ('hobby', 'Hobby')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remote',
            field=models.CharField(choices=[('full_remote', 'Télétravail complet'), ('no_remote', 'Pas de télétravail'), ('hybrid', 'Hybride'), ('no_pref', 'Sans préférence')], default='no_pref', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rqth',
            field=models.CharField(choices=[('with_rqth', 'Avec RQTH'), ('without_rqth', 'Sans RQTH'), ('dont_say', 'N/A')], default='dont_say', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Qui sommes-nous ?'),
        ),
        migrations.AlterField(
            model_name='company',
            name='diversity_and_inclusion_policy',
            field=models.TextField(verbose_name='Diversité et inclusion'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Site Web'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_contract_type',
            field=models.CharField(choices=[('contract', 'Expérience professionnelle'), ('training', 'Formation'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('pro', 'Expérience professionnelle'), ('personal', 'Personnelle'), ('training', 'Formation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current_position',
            field=models.BooleanField(default=False, verbose_name='Poste actuel'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_part_time',
            field=models.BooleanField(default=False, verbose_name='Temps partiel'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='benefits',
            field=models.TextField(verbose_name='Avantages'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuroa_app.company', verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contract_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('self_employed', 'Auto-entrepreneur'), ('internship', 'Stage'), ('work_study', 'Alternance'), ('civic_service', 'Service civique'), ('other', 'Autre')], max_length=73, verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(verbose_name='Descriptif du poste'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='is_part_time',
            field=models.BooleanField(default=False, verbose_name='Temps partiel'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Intitulé du poste'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='publication_date',
            field=models.DateField(auto_now=True, verbose_name='Date de mise en ligne'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='recruitment_process',
            field=models.TextField(verbose_name='Processus de recrutement'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='remotes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full_remote', 'Télétravail complet'), ('no_remote', 'Pas de télétravail'), ('hybrid', 'Hybride')], max_length=28, verbose_name='Télétravail'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='skills',
            field=models.TextField(verbose_name='Compétences essentielles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidat'), ('recruiter', 'Recruteur'), ('admin', 'Admin')], default='candidate', max_length=20),
        ),
    ]
