# Generated by Django 5.1.6 on 2025-03-11 11:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0016_alter_company_options_alter_joboffer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='mobilities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('on_foot', 'À pied'), ('wheelchair', 'En fauteuil roulant'), ('public_transport', 'En transports en commun'), ('bicycle', 'À vélo / trotinette'), ('car', 'En voiture / moto')], max_length=47, null=True, verbose_name='Mobilités'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('skill', 'Compétence'), ('cause', 'Cause'), ('hobby', 'Hobby')], max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rqth',
            field=models.CharField(choices=[('with_rqth', 'Avec RQTH'), ('without_rqth', 'Sans RQTH'), ('dont_say', 'Ne souhaite pas répondre')], default='dont_say', max_length=20),
        ),
    ]
