# Generated by Django 5.1.6 on 2025-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0017_candidate_mobilities_alter_attribute_attribute_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Détails'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_contract_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('independent', 'Indépendant'), ('internship', 'Stage'), ('work_study', 'Alternance'), ('civic_service', 'Service civique'), ('other', 'Autre')], default='other', max_length=50, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('pro', 'Expérience professionnelle'), ('personal', 'Activité personnelle'), ('training', 'Formation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='is_current_position',
            field=models.BooleanField(default=False, verbose_name="J'occupe actuellement ce poste"),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='organization',
            field=models.CharField(max_length=50, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='url',
            field=models.URLField(blank=True, verbose_name='Lien'),
        ),
    ]
