# Generated by Django 5.1.6 on 2025-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0019_candidate_attributes_delete_candidateattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='favorite_job_offers',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='neuroa_app.joboffer'),
        ),
    ]
