# Generated by Django 5.1.6 on 2025-03-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0020_candidate_favorite_job_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='favorite_job_offers',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('skill', 'Compétence'), ('cause', 'Causes, engagements'), ('hobby', 'Loisirs, passions')], max_length=20),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('saved', 'Sauvegardée'), ('sent', 'Envoyée')], default='saved', max_length=20)),
                ('comments', models.TextField(verbose_name='Descriptif de la candidature')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='Date de postulation')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='neuroa_app.candidate')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuroa_app.joboffer', verbose_name="Offres d'emploi")),
            ],
        ),
    ]
