# Generated by Django 5.1.6 on 2025-04-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0022_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_status',
            field=models.CharField(choices=[('saved', 'Sauvegardée'), ('sent', 'Envoyée'), ('exchange', "Phase d'échage"), ('refused', 'Candidature refusée'), ('accepted', 'Embauché')], default='saved', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Détails'),
        ),
    ]
