# Generated by Django 5.1.6 on 2025-04-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0023_alter_application_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Descriptif de la candidature'),
        ),
    ]
