# Generated by Django 5.1.6 on 2025-04-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0024_alter_application_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Poste/Intitulé'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Date de début'),
        ),
    ]
