# Generated by Django 5.1.6 on 2025-04-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0026_alter_candidate_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remote',
            field=models.CharField(blank=True, choices=[('no_pref', 'Sans préférence'), ('full_remote', 'Télétravail complet'), ('no_remote', 'Pas de télétravail'), ('hybrid', 'Hybride')], default='no_pref', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rqth',
            field=models.CharField(blank=True, choices=[('dont_say', 'Ne souhaite pas répondre'), ('with_rqth', 'Avec RQTH'), ('without_rqth', 'Sans RQTH')], default='dont_say', max_length=20),
        ),
    ]
