# Generated by Django 5.1.6 on 2025-05-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0029_alter_candidate_candidate_remote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remote',
            field=models.CharField(choices=[('no_pref', 'Sans préférence'), ('full_remote', 'Télétravail complet'), ('no_remote', 'Pas de télétravail'), ('hybrid', 'Hybride')], default='no_pref', max_length=20, verbose_name='Télétravail souhaité'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rqth',
            field=models.CharField(choices=[('dont_say', 'Ne souhaite pas répondre'), ('with_rqth', 'Avec RQTH'), ('without_rqth', 'Sans RQTH')], default='dont_say', max_length=20, verbose_name='RQTH'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='special_needs_comments',
            field=models.CharField(max_length=255, verbose_name="Besoins d'adaptation"),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Nom'),
        ),
    ]
