# Generated by Django 5.1.6 on 2025-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0030_alter_candidate_candidate_remote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remote',
            field=models.CharField(blank=True, choices=[('no_pref', 'Sans préférence'), ('full_remote', 'Télétravail complet'), ('no_remote', 'Pas de télétravail'), ('hybrid', 'Hybride')], max_length=20, null=True, verbose_name='Télétravail souhaité'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='rqth',
            field=models.CharField(blank=True, choices=[('dont_say', 'Ne souhaite pas répondre'), ('with_rqth', 'Avec RQTH'), ('without_rqth', 'Sans RQTH')], max_length=20, null=True, verbose_name='RQTH'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Présentation'),
        ),
    ]
