# Generated by Django 5.1.6 on 2025-05-05 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0031_alter_candidate_candidate_remote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='is_part_time',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='is_part_time',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_work_time',
            field=models.CharField(choices=[('full', 'Temps plein'), ('partial', 'Temps partiel')], default=django.utils.timezone.now, max_length=50, verbose_name='Temps de travail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_offer_work_time',
            field=models.CharField(choices=[('full', 'Temps plein'), ('partial', 'Temps partiel')], default=django.utils.timezone.now, max_length=50, verbose_name='Temps de travail'),
            preserve_default=False,
        ),
    ]
