# Generated by Django 5.1.6 on 2025-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0032_remove_experience_is_part_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('skill', 'Compétences'), ('hobby', 'Loisirs, passions'), ('cause', 'Causes, engagements')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_contract_type',
            field=models.CharField(blank=True, choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('freelance', 'Freelance'), ('independent', 'Indépendant'), ('internship', 'Stage'), ('work_study', 'Alternance'), ('civic_service', 'Service civique'), ('other', 'Autre')], default='other', max_length=50, null=True, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_type',
            field=models.CharField(choices=[('pro', 'Expériences professionnelles'), ('personal', 'Activités personnelles'), ('training', 'Formations')], max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experience_work_time',
            field=models.CharField(blank=True, choices=[('full', 'Temps plein'), ('part', 'Temps partiel')], max_length=50, null=True, verbose_name='Temps de travail'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='job_offer_work_time',
            field=models.CharField(choices=[('full', 'Temps plein'), ('part', 'Temps partiel')], max_length=50, verbose_name='Temps de travail'),
        ),
    ]
