# Generated by Django 5.1.6 on 2025-05-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0033_alter_attribute_attribute_type_and_more'),
        ('neuroa_app', '0033_remove_experience_end_date_and_more'),
    ]

    operations = [
    ]
