# Generated by Django 5.1.6 on 2025-06-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0034_merge_20250516_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='start_month',
            field=models.IntegerField(verbose_name='Mois de début'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(verbose_name='Année de début'),
        ),
    ]
