# Generated by Django 5.1.6 on 2025-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuroa_app', '0035_alter_experience_start_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='is_current_position',
            field=models.BooleanField(default=False, verbose_name='Je pratique actuellement cette activité'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Titre'),
        ),
    ]
